/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PostRouteImport } from './routes/post'
import { Route as RemoteGolfJobsRouteImport } from './routes/remote-golf-jobs'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as EmployerSlugRouteImport } from './routes/employer.$slug'
import { Route as GolfJobsInStateRouteImport } from './routes/golf-jobs-in.$state'
import { Route as GolfJobsCategoryRouteImport } from './routes/golf-jobs.$category'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as JobsStateRoleRouteImport } from './routes/jobs.$state.$role'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteGolfJobsRoute = RemoteGolfJobsRouteImport.update({
  id: '/remote-golf-jobs',
  path: '/remote-golf-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerSlugRoute = EmployerSlugRouteImport.update({
  id: '/employer/$slug',
  path: '/employer/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GolfJobsInStateRoute = GolfJobsInStateRouteImport.update({
  id: '/golf-jobs-in/$state',
  path: '/golf-jobs-in/$state',
  getParentRoute: () => rootRouteImport,
} as any)
const GolfJobsCategoryRoute = GolfJobsCategoryRouteImport.update({
  id: '/golf-jobs/$category',
  path: '/golf-jobs/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsStateRoleRoute = JobsStateRoleRouteImport.update({
  id: '/jobs/$state/$role',
  path: '/jobs/$state/$role',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/post': typeof PostRoute
  '/remote-golf-jobs': typeof RemoteGolfJobsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscribe': typeof SubscribeRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/employer/$slug': typeof EmployerSlugRoute
  '/golf-jobs-in/$state': typeof GolfJobsInStateRoute
  '/golf-jobs/$category': typeof GolfJobsCategoryRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/jobs/$state/$role': typeof JobsStateRoleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/post': typeof PostRoute
  '/remote-golf-jobs': typeof RemoteGolfJobsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscribe': typeof SubscribeRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/employer/$slug': typeof EmployerSlugRoute
  '/golf-jobs-in/$state': typeof GolfJobsInStateRoute
  '/golf-jobs/$category': typeof GolfJobsCategoryRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs': typeof JobsIndexRoute
  '/jobs/$state/$role': typeof JobsStateRoleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/post': typeof PostRoute
  '/remote-golf-jobs': typeof RemoteGolfJobsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscribe': typeof SubscribeRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/employer/$slug': typeof EmployerSlugRoute
  '/golf-jobs-in/$state': typeof GolfJobsInStateRoute
  '/golf-jobs/$category': typeof GolfJobsCategoryRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/': typeof JobsIndexRoute
  '/jobs/$state/$role': typeof JobsStateRoleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/post'
    | '/remote-golf-jobs'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/subscribe'
    | '/collections/$slug'
    | '/employer/$slug'
    | '/golf-jobs-in/$state'
    | '/golf-jobs/$category'
    | '/jobs/$id'
    | '/jobs/'
    | '/jobs/$state/$role'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/post'
    | '/remote-golf-jobs'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/subscribe'
    | '/collections/$slug'
    | '/employer/$slug'
    | '/golf-jobs-in/$state'
    | '/golf-jobs/$category'
    | '/jobs/$id'
    | '/jobs'
    | '/jobs/$state/$role'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/post'
    | '/remote-golf-jobs'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/subscribe'
    | '/collections/$slug'
    | '/employer/$slug'
    | '/golf-jobs-in/$state'
    | '/golf-jobs/$category'
    | '/jobs/$id'
    | '/jobs/'
    | '/jobs/$state/$role'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  PostRoute: typeof PostRoute
  RemoteGolfJobsRoute: typeof RemoteGolfJobsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubscribeRoute: typeof SubscribeRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  EmployerSlugRoute: typeof EmployerSlugRoute
  GolfJobsInStateRoute: typeof GolfJobsInStateRoute
  GolfJobsCategoryRoute: typeof GolfJobsCategoryRoute
  JobsIdRoute: typeof JobsIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
  JobsStateRoleRoute: typeof JobsStateRoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote-golf-jobs': {
      id: '/remote-golf-jobs'
      path: '/remote-golf-jobs'
      fullPath: '/remote-golf-jobs'
      preLoaderRoute: typeof RemoteGolfJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/$slug': {
      id: '/employer/$slug'
      path: '/employer/$slug'
      fullPath: '/employer/$slug'
      preLoaderRoute: typeof EmployerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/golf-jobs-in/$state': {
      id: '/golf-jobs-in/$state'
      path: '/golf-jobs-in/$state'
      fullPath: '/golf-jobs-in/$state'
      preLoaderRoute: typeof GolfJobsInStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/golf-jobs/$category': {
      id: '/golf-jobs/$category'
      path: '/golf-jobs/$category'
      fullPath: '/golf-jobs/$category'
      preLoaderRoute: typeof GolfJobsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$state/$role': {
      id: '/jobs/$state/$role'
      path: '/jobs/$state/$role'
      fullPath: '/jobs/$state/$role'
      preLoaderRoute: typeof JobsStateRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  PostRoute: PostRoute,
  RemoteGolfJobsRoute: RemoteGolfJobsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubscribeRoute: SubscribeRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  EmployerSlugRoute: EmployerSlugRoute,
  GolfJobsInStateRoute: GolfJobsInStateRoute,
  GolfJobsCategoryRoute: GolfJobsCategoryRoute,
  JobsIdRoute: JobsIdRoute,
  JobsIndexRoute: JobsIndexRoute,
  JobsStateRoleRoute: JobsStateRoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
